### ISSUE TITLE
Inconsistency of pressure variable in convection parametrizations

### ISSUE THREAD

**Issue by dmey** [SpeedyWeather/SpeedyWeather.jl#171]
I noticed surface pressure `pres` is overloaded to also mean normalized surface pressure in the current convection parameteization
https://github.com/milankl/SpeedyWeather.jl/blob/4b3176764bdd4897978ce2312948bd0d2f03da79/src/convection.jl#L43

this is also confirmed in the tests where a normlised pressure is used intsead
https://github.com/milankl/SpeedyWeather.jl/blob/4b3176764bdd4897978ce2312948bd0d2f03da79/test/convection.jl#L10

I think this should be changed throughout to make clear this is not the surface pressure in hPa. 

@milankl separate and perhaps for later but I find `pres` to mean surface pressure unclear (i.e. when I first saw it I was expending a vector of pressures in hPa!), can this be changed to `surf_pres` or something like that?

**Comment by milankl** [comment]
In the numerics of speedy there is only surface pressure ever used, in order to get "pressure" on other layers the geopotential is computed on those (with the surface geopotential being the orography times gravity). Hence, yes we had called it at some point `pres_surf` but realised it's a bit unnecessary as `pres` without `_surf` doesn't actually exist. Furthermore, for the `ShallowWaterModel` `pres` actually refers to the interface displacement which is often called eta. This is not to be confusing, but simply because we want to reuse that variable in that case -- and it has conceptually a very similar meaning.

**Comment by milankl** [comment]
@white-alistair which logic did you follow in `convection.jl`, is there something we should change?

**Comment by milankl** [comment]
Note that we can do separate things in the dynamics vs the parameterizations. Why I'm hesitating in the dynamics is that `pres` may have units of [log(Pa)] in the `PrimitiveEquationModel` but [m] in the `ShallowWaterModel`. So being more specific than `pres` does not actually help because it creates even more confusion for the respectively other model. Happy to discuss this more, but for clarity in the parameterizations, where, I agree, clarification with units is more important, we could start by changing
https://github.com/milankl/SpeedyWeather.jl/blob/2da381d2eea75556b306d5e3a2fc954c921c0f49/src/column_variables.jl#L81-L83
meaning, you can add and change all pressure related variables as long as you pull `D.surface.pres_grid[ij]` which is the logarithm of surface pressure in Pa from the dynamics. So feel free to rename the variable to `C.log_surf_pres` in `ColumnVariables` and add `surf_pres`, `norm_surf_pres` etc.

**Comment by milankl** [comment]
Update @dmey, in the physics `ColumnVariables` now has two fields
```julia
    # (log) pressure per layer
    const ln_pres::Vector{NF}    # logarithm of pressure [log(hPa)]
    const pres::Vector{NF}       # pressure [hPa]
```
In the dynamics we still have `pres` meaning the log of surface pressure [log(Pa)] in the PrimitiveEquation model or the layer height [m] in the shallow water model. Any strong feelings @white-alistair ? Now's the time probably as I'm addressing #255 anyway

**Comment by white-alistair** [comment]
Hey, no strong feelings on my part. Your suggestion LGTM :+1:
