### ISSUE TITLE
Discuss general API

### ISSUE THREAD

**Issue by dmey** [SpeedyWeather/SpeedyWeather.jl#184]
This is perhaps not the best place to discuss but I would like to better understand what general API you have in mind for SpeedyWeather.jl. Especially for dynamics and parametrization schemes and passing of variables and parameters. I would like to try avoid pitfalls of other models.

**Comment by milankl** [comment]
In general I was thinking towards a type or module-modularity approach. This is why I've spend a good amount of time to get the grid-flexible spectral transform going because it does exactly that. The logic that this uses is the following
- `run_speedy(Grid=MyGrid)` accepts any `MyGrid<:AbstractGrid` as long as a set of methods are defined for it (something like `get_quadrature_weights(MyGrid,...)`)
- A few grids `<:AbstractGrid` are already defined in SpeedyWeather.jl but one can define additional ones externally (in other packages or whereever) and pass them on as an argument

A grid is conceptually a data structure, so it's implemented as a `struct` and therefore this API relies on type-modularity. Talking about parameterizations, they will be probably more like set of functions to execute instead of the default ones if we want them modular. Sure, the functions could rely on precomputed arrays (like ML inference), but so I'm thinking about putting a parameterization scheme into a module (which can be its own package, but doesn't have to be)

So I'm thinking about doing something like
```julia
using SpeedyWeather
using MyPrecipitationScheme
run_speedy(precipitation_scheme=MyPrecipitationScheme)
```
whereby we define what functions the scheme should provide. In the case of precipitation, it should ultimately update the temperature and humidity tendencies, but how it does that is up to the scheme. SpeedyWeather.jl would also dictate which arguments those functions get, but this will likely be as general as `::ColumnVariables` (meaning we will make the constraint that all parameterizations only work in the vertical) and `M::PrimitiveEquationModel` (such that one could define a parameterization that uses a very different set of parameters from m.parameters etc)

**Comment by milankl** [comment]
referencing the discussion on subpackages: #231

**Comment by milankl** [comment]
Closing this as we seem to have settled on the idea that new schemes are types not modules. That way they fit in the type hierarchy and we can dispatch over them. See also #320
