### ISSUE TITLE
Merging strategy

### ISSUE THREAD

**Issue by dmey** [SpeedyWeather/SpeedyWeather.jl#214]
@milankl I noticed that the last commits were not squashed in #177. I am not sure if this was on purpose but in any case it would be good to discuss this for the future. In my other projects I tend to keep `main` as clean as possible and squash any commit from PRs but you may have other reasons for not doing this. Do you have any preference that we should follow from this point forward when merging PRs?

**Comment by milankl** [comment]
I honestly don't mind that much. I usually try to give telling messages to commits so that it's clear which model part is affected by one. I agree that your commit "remove newline" isn't and so should have been squashed. But "fband" is almost okay, but in general I'd rather have something like "remove xyz in radset!" so that it's clearer from the commit history which parts of the model where affected. Honestly, I often end up tweaking several corners of the model when I implement something, such that I'd rather not have them squashed to better record which model parts where affected. Maybe in short:

- if pull requests affect isolated parts of the model; you can use short, generic commit messages and squash
- else: rather use more specific commit messages and don't squash

Does that make sense?

**Comment by milankl** [comment]
I'm happy to make that decision upon merging, but I'd rather keep the labels topical, meaning that if I want to find all issues/pull requests on parameterizations then I klick on the label parameterizations.
