### ISSUE TITLE
First output timestep is < 6 hours.

### ISSUE THREAD

**Issue by natgeo-wong** [SpeedyWeather/SpeedyWeather.jl#237]
The first timestep has a tendency to be less than 6 hours.

```
julia> run_speedy(ShallowWater,orography=NoOrography,n_days=100,trunc=42,Δt_at_T31=18*42/31,seed=123,output=true,implicit_α=1);

julia> ds = NCDataset("run-0003/output.nc");

julia> ds["time"][:]
401-element Vector{Dates.DateTime}:
 2000-01-01T00:00:00
 2000-01-01T05:24:00
 2000-01-01T11:24:00
 2000-01-01T17:24:00
```

**Comment by milankl** [comment]
This is because the leapfrog time stepping requires the first time step to be calculated with Euler, but at half the dt, then the next time step is also half dt but using leapfrog and then it uses the normal time step afterwards. So the output step is one too early, but 6h after that.

We can probably fix that by adjusting `output_every_n_steps` somehow inside `first_timesteps!` so that the half steps are correctly accounted for.

**Comment by milankl** [comment]
As an overview: Higher resolution reduces the discrepancy of the first output time step from 6hrs. But also the time steps after that are *at most* 6 hours if `output_dt=6`
```julia
T= 31, 00:00:00 05:00:00 11:00:00 17:00:00 23:00:00, actual dt = 6 hours
T= 42, 00:00:00 05:10:06 11:04:30 16:58:54 22:53:18, actual dt = 5 hours, 54 minutes, 24 seconds
T= 63, 00:00:00 05:24:52 11:19:16 17:13:40 23:08:04, actual dt = 5 hours, 54 minutes, 24 seconds
T= 85, 00:00:00 05:28:00 11:17:52 17:07:44 22:57:36, actual dt = 5 hours, 49 minutes, 52 seconds
T=127, 00:00:00 05:43:53 11:42:24 17:40:55 23:39:26, actual dt = 5 hours, 58 minutes, 31 seconds
T=255, 00:00:00 05:50:24 11:48:06 17:45:48 23:43:30 , actual dt = 5 hours, 57 minutes, 42 seconds
```
