### ISSUE TITLE
Literated example with the animation that is currently in `README`?

### ISSUE THREAD

**Issue by navidcy** [SpeedyWeather/SpeedyWeather.jl#297]
Would that be a good idea?

Or the docs can include a simpler/less computationally demanding example?

**Comment by milankl** [comment]
I agree, we should make sure that there are different examples, probably all at relatively low resolution so that can easily be reproduced. I would definitely want that in the documentation for v0.5 but probably one of the last issues to be resolved so that last minute changes in the `run_speedy` interface don't have to be backpropagated to the docs

**Comment by navidcy** [comment]
okie!

**Comment by milankl** [comment]
I think for now I'm happy with the examples in the documentation and they are somewhat easily reproducible by copying over the presented code snippets. I think that's good enough for now. The examples aren't complicated enough yet to require a whole experiment.jl file so I'm closing this issue for now, but anyone feel free to reopen if this should be added!

**Comment by navidcy** [comment]
Noice!
