### ISSUE TITLE
Query about computational resources

### ISSUE THREAD

**Issue by sophia-wright-blue** [SpeedyWeather/SpeedyWeather.jl#342]
thank you so much for releasing this amazing repo!

it'd be very helpful to have some info on the computational resources required to run various simulations available with this repo for different grids - for e.g., the "Example use" illustration in the README says it takes 5 seconds for that particular simulation - on how many CPU cores was this run and how much RAM was required.

it'd be great to know what resolution and what kind of simulations are possible on a single node - say with 16 physical cores and 64GB RAM

thank you!

**Comment by milankl** [comment]
Thanks for your interest!

At the moment the model is only multi-threaded, that means using 16 CPUs will be somewhat faster than using 1, but only about 4x so and not 16x. I believe we can improve the scaling here, but I haven't done it yet - if you want to get this rolling I'd be happy to advise you because I have some ideas how we can make the multi-threading faster.

Having said that, I never systematically tested the performance. I know it's about 500years/day on a single core at T31 8 levels, and it quickly drops to 1year/day for T255 I believe, but never really tested as I said. When you run the model it'll tell you the speedy in years/day, days/day in the progress bar though.

The RAM question is an interesting one and I just found a nice way to test this
```julia
julia> spectral_grid = SpectralGrid()
SpectralGrid:
 Spectral:   T31 LowerTriangularMatrix{Complex{Float32}}, radius = 6.371e6 m
 Grid:       3168-element, 48-ring OctahedralGaussianGrid{Float32} (quadratic)
 Resolution: 401km (average)
 Vertical:   8-level SigmaCoordinates

julia> model = PrimitiveDryModel(;spectral_grid);

julia> simulation = initialize!(model);

julia> Base.summarysize(simulation)/1000^2
3.176625

julia> Base.summarysize(simulation.prognostic_variables)/1000^2
0.23198

julia> Base.summarysize(simulation.diagnostic_variables)/1000^2
2.33694

julia> Base.summarysize(simulation.model)/1000^2
0.606777
```
So at the default T31 8 levels it's 3MB, 230KB the prognostic variables, 2.3MB the diagnostic variables and 600KB the model (most of them should be the Legendre polynomials.

At T127 this changes to (still 8 levels)
```julia
julia> spectral_grid = SpectralGrid(trunc=127)
SpectralGrid:
 Spectral:   T127 LowerTriangularMatrix{Complex{Float32}}, radius = 6.371e6 m
 Grid:       40320-element, 192-ring OctahedralGaussianGrid{Float32} (quadratic)
 Resolution: 112km (average)
 Vertical:   8-level SigmaCoordinates

julia> model = PrimitiveDryModel(;spectral_grid);

julia> simulation = initialize!(model);

julia> Base.summarysize(simulation.model)/1000^2
11.382681

julia> Base.summarysize(simulation.diagnostic_variables)/1000^2
30.206508

julia> Base.summarysize(simulation.prognostic_variables)/1000^2
3.36158
```
11MB model, 30MB diagnostic vars, 4MB prognostic vars, ~45MB in total

At T1023 we'd have with 60 levels
```julia
julia> spectral_grid = SpectralGrid(trunc=1023,nlev=60)
SpectralGrid:
 Spectral:   T1023 LowerTriangularMatrix{Complex{Float32}}, radius = 6.371e6 m
 Grid:       2386944-element, 1536-ring OctahedralGaussianGrid{Float32} (quadratic)
 Resolution: 14.6km (average)
 Vertical:   60-level SigmaCoordinates

julia> model = PrimitiveDryModel(;spectral_grid);

julia> simulation = initialize!(model);

julia> Base.summarysize(simulation.prognostic_variables)/1000^2
1522.843788

julia> Base.summarysize(simulation.diagnostic_variables)/1000^2
12930.105884

julia> Base.summarysize(simulation.model)/1000^2
2142.693145
```
So 1.5GB progn, 13GB diagn, 2GB model

**Comment by milankl** [comment]
But not that at the moment you can run the barotropic and shallow water model at T1023 and beyond, but it's not multi-threaded, but the primitive models currently are unstable for >T170 with >20-30 levels ... There are some open issues on this you are more than welcome to contribute to fix them!

**Comment by sophia-wright-blue** [comment]
thank you so much for the detailed response! that is very helpful!! I look forward to understanding the use of this model better and hopefully contributing soon as well!

**Comment by milankl** [comment]
Currently writing some examples into the documentation, stay tuned!
