### ISSUE TITLE
Output time axis: option to adhere to output_dt exactly

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [SpeedyWeather/SpeedyWeather.jl#416]
Currently, the specified `output_dt` is only approximately kept, as also demonstrated in the documentation on the netCDF output section. 

For long trajectories and small `output_dt` the offset can become quite large, quite quickly. 

One way of solving it would be to interpolate with an external library. But I wonder if we also should offer an alternative. 

What I could implement is the following:

Introduce an optional kwarg to the time stepper (so `Leapfrog`) for `output_dt`. If it is provided, then the scaled(*) `Δt_at_T31` is adjusted to be the closest divisor of `output_dt` of its input argument (or default value if no input for `Δt_at_T31` is provided).  When `output_dt` is divisible by the scaled `Δt_at_T31`, then the time output is kept exactly. 

(*) scaled with trunc, as done currently

What do you think? I definitely need this for myself, but I could also turn it into a PR.

**Comment by milankl** [comment]
I'd be happy for you and go forward implementing these ideas, if I understand an example would be

You want output every 6hrs = 21600s? At your resolution you need a time step of approximately 125s for stability, but that's not a divisor of 21600s so make the time step slightly smaller, 120s so that we would do output every 21600/120 = 180 time steps. 

In that sense we would interpret `Δt_at_T31` as the largest possible time step but the real time step would be somewhat smaller. At the moment our time step is always an integer (even if represented as float) but we can relax that too. Because in the example above if 125s would be turned into 120s that would make the simulation also 4% slower. However, if we said, output every 21600s, ideal time step would be 125s so that's every 172.8 time steps, problem, so let's round this up to 173 time steps of 21600s/173 = 124.855...s the slow down would be insignificant.

I'd actually suggest to add a `adjust_with_output=true/false` to `Leapfrog` for which then the method as you suggest is done. That way it's more verbose that even if you choose a specific time step in `Leapfrog` it may get altered slightly depending on the output time step.

We would then just need to make sure that the model time is counted up correctly

https://github.com/SpeedyWeather/SpeedyWeather.jl/blob/b047723d187505438ab981ab67da89d76aeb0333/src/dynamics/time_integration.jl#L293

Because that's the time that's used to write the time axis of the netcdf output here

https://github.com/SpeedyWeather/SpeedyWeather.jl/blob/b047723d187505438ab981ab67da89d76aeb0333/src/output/output.jl#L385-L386

In general you are free to change this as you think is best, only a few things I'd like to avoid:

- interpolation of two time steps during output. For most variables we only have one time step available in grid-point space so that would add either memory or compute, both which I'd like to avoid
- irregular time steps in output, e.g. when the closest time step to output_dt=6hours is picked, which would guarantee that every 4th time step is approximately 6am,12am,6pm,midnight and doesn't run away, but it makes a lot of statistics really ugly

**Comment by maximilian-gelbrecht** [comment]
> I'd be happy for you and go forward implementing these ideas, if I understand an example would be
> 
> You want output every 6hrs = 21600s? At your resolution you need a time step of approximately 125s for stability, but that's not a divisor of 21600s so make the time step slightly smaller, 120s so that we would do output every 21600/120 = 180 time steps.
> 
> In that sense we would interpret `Δt_at_T31` as the largest possible time step but the real time step would be somewhat smaller. At the moment our time step is always an integer (even if represented as float) but we can relax that too. Because in the example above if 125s would be turned into 120s that would make the simulation also 4% slower. However, if we said, output every 21600s, ideal time step would be 125s so that's every 172.8 time steps, problem, so let's round this up to 173 time steps of 21600s/173 = 124.855...s the slow down would be insignificant.
> 
> I'd actually suggest to add a `adjust_with_output=true/false` to `Leapfrog` for which then the method as you suggest is done. That way it's more verbose that even if you choose a specific time step in `Leapfrog` it may get altered slightly depending on the output time step.
> 
> We would then just need to make sure that the model time is counted up correctly
> 
> https://github.com/SpeedyWeather/SpeedyWeather.jl/blob/b047723d187505438ab981ab67da89d76aeb0333/src/dynamics/time_integration.jl#L293
> 
> Because that's the time that's used to write the time axis of the netcdf output here
> 
> https://github.com/SpeedyWeather/SpeedyWeather.jl/blob/b047723d187505438ab981ab67da89d76aeb0333/src/output/output.jl#L385-L386
> 
> In general you are free to change this as you think is best, only a few things I'd like to avoid:
> 
> * interpolation of two time steps during output. For most variables we only have one time step available in grid-point space so that would add either memory or compute, both which I'd like to avoid
> * irregular time steps in output, e.g. when the closest time step to output_dt=6hours is picked, which would guarantee that every 4th time step is approximately 6am,12am,6pm,midnight and doesn't run away, but it makes a lot of statistics really ugly

Yes, exactly. 

Great, then I'll work on a PR. I am on vacation next week, but maybe I'll already get this done tomorrow. Let's see.

**Comment by milankl** [comment]
When implemtenting this could you also have a thought (no action needed unless it's easy) at #417
