### ISSUE TITLE
[JOSS review] Zenodo archival

### ISSUE THREAD

**Issue by slayoo** [SpeedyWeather/SpeedyWeather.jl#448]
It seems that the Zenodo release archival stopped working at v0.4.0: https://zenodo.org/doi/10.5281/zenodo.6510139
It would be very beneficial to have it up an running again.

**Comment by slayoo** [comment]
(in relation to https://github.com/openjournals/joss-reviews/issues/6323)

**Comment by navidcy** [comment]
This coincides with when the repo moved from @milankl's account to SpeedyWeather org. Probably it's related!
I'll try to sort this out.

**Comment by navidcy** [comment]
@milankl I think you need to do it because I don't have admin rights for the organization. We need to give third-party access to Zenodo in the organization; see https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization

**Comment by milankl** [comment]
Thanks for spotting this. Yes, I realised this a month ago or so too. It was because of the transition to the SpeedyWeather org as Navid says. I've given zenodo the respective rights to the SpeedyWeather org and this should work now, leaving this issue open now that we can check after the next release though!

**Comment by navidcy** [comment]
We might need to update the zenodo doi?
