### ISSUE TITLE
RingGrids: N-dim Matrix/Array constructors 

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [SpeedyWeather/SpeedyWeather.jl#570]
While revising the `OutputWriter` (#571), I noticed some inconsistencies with how the `RingGrids` can be initialised from data. 

So in 2D everything is as it is before: 
```Julia 
map = randn(Float32, 8, 4)
FullGaussianGrid(map) # -> 32-element, 4-ring FullGaussianGrid{Float64}
```

But when we add more dimensions to the data, the following happens: 
```Julia 
map = rand(Float32, 8, 4, 2) # in our logic in the other parts of the code, these are 2 (8x4) maps 
FullGaussianGrid(map) # -> 8×4×2, 2-ring FullGaussianArray{Float64, 3, Array{Float64, 3}}:
```
So this returns a 4D `8×4×2, 2-ring FullGaussianArray{Float64, 3, Array{Float64, 3}}:`, even though I would expect it to just return a `32x2 - 4-ring FullGaussianGrid{Float64}`. At least in my opinion, this would be consistent with how we handle the multidimensional data in the other functions. 

I don't directly see another way to generate a `RingGrid` from a full array currently. 

Also, the documentation should probably be extended to include a section for N-dim RingGrids.

**Comment by milankl** [comment]
Thinking about this, we should make the second version (horizontal dimensions flattened) the default for consistency with other grids. But yes, it would be great to have an easy constructor for the full grids that also allows for a non-flattened input.

I see your desire to have a new function `FullGrid_from_Array` but that's not really clear whether it's a flattened or matrix representation for the horizontal dimensions no? For me this sounds like an option rather than a new function, you think we could implement this using a keyword argument, something like

```julia
FullGaussianGrid(map, horizontal_as=Matrix)
```

Or maybe `horizontal_input_as=Matrix` vs `Vector`? similar to how we use `as=Matrix` for `size(::LowerTriangularMatrices)`? Maybe one would understand this keyword more as affecting the full Gaussian grid rather than the interpretation of the input...

**Comment by maximilian-gelbrecht** [comment]
Yeah, that would work as well. I can change my PR like that this afternoon
