### ISSUE TITLE
Driven by reanalysis data

### ISSUE THREAD

**Issue by Richard2323111** [SpeedyWeather/SpeedyWeather.jl#576]
Dear Prof Kloewer and All,

I'm very interested in SpeedyWeather, but very new to the atmosphere model. I ask you how it could be possible to drive the SpeedyWeather by reanalysis data like ERA5.

Many thanks.
Finhowe Chan

**Comment by milankl** [comment]
Hi Finhowe, thanks for your interest!! You will need to specify in a bit more detail of what you mean by "drive by ERA5". As an atmospheric model, SpeedyWeather uses variables like wind, temperature and humidity. These have forcing terms that can originate or include data which could come from ERA5. Most atmospheric models are primarily driven by radiation, so a tendency on the temperature equation. That's an external source of energy that's not calculated within the model but provided. But there are other sources of forcing too, like interaction with the ocean, sea ice, land, land ice, vegetation and humans too. Most of these are fluxes, e.g. every atmospheric model will have surface fluxes that describe how much heat (for temperature tendency), fresh water (for humidity) and momentum (for wind) are going into or coming out of the ocean. If you know what you want to do you can define new schemes to replace our radiation, surface fluxes, sea surface temperatures etc, e.g. replacing `SurfaceEvaporation` or `SurfaceHeatFlux`, but there's many ways to do this and so there's no "force with ERA5" button unfortunately. For an ocean model this is more clearly defined as an ocean model is almost exclusively driven by atmospheric fluxes, which could be computed from ERA5. But for the atmosphere that's not as well defined because ERA5 overlaps with what SpeedyWeather simulates too.
