### ISSUE TITLE
Use logging infrastructure for feedback messages

### ISSUE THREAD

**Issue by giordano** [SpeedyWeather/SpeedyWeather.jl#68]
It may be useful to use the [logging infrastructure](https://docs.julialang.org/en/v1/stdlib/Logging/) for the [feedback messages](https://github.com/milankl/SpeedyWeather.jl/blob/8bc0276b433cd8576c19c6e6d71bb151da8893ed/src/feedback.jl).  One benefit is that you can actually check the content of logged messages with [`@test_logs`](https://docs.julialang.org/en/v1/stdlib/Test/#Test.@test_logs) and this doesn't show up when running the tests.  Also, you may consider using [`ProgressMeter.jl`](https://github.com/timholy/ProgressMeter.jl) for the progress bar.

**Comment by giordano** [comment]
I don't remember exactly, it has been a while since I last played with this package.

In the first message of this thread I linked the file https://github.com/milankl/SpeedyWeather.jl/blob/8bc0276b433cd8576c19c6e6d71bb151da8893ed/src/feedback.jl, suggesting to not use custom printing and instead to use Julia's own logging infrastructure and ProgressMeter.jl (the latter has been addressed in #69), is there any other information messages that are still printed to stdout?

**Comment by milankl** [comment]
> is there any other information messages that are still printed to stdout?

No there aren't at the moment. While I like the idea of logging, in practice I didn't end up using it, because in most cases I didn't need a verbose/non-verbose feature. Sure I still add some `println` in development just to quickly check that the code I'm working on is actually executed (which sometimes if you change the function signature can be hard to tell). But none of these were permanent.

Having said that, I do see space for a verbose mode that prints regularly quantities like total kinetic energy/maximum velocity to stdout, so that one gets feedback about the model state while it's running. Telling the compiler via `Logging` to execute/ignore these lines might then come handy.

**Comment by milankl** [comment]
Closing this as the progressmeter is awesome, we still use it as before, but I never ended up using the logging infrastructure...
